import type { Metadata } from "next";
import  {Sidebar}  from "@components/layout/Sidebar";
import  {Navbar}  from "@components/layout/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative bg-yellow-50 overflow-hidden max-h-screen">
        
        {/* Navbar */}
        <Navbar />
        {/* Navbar */}

        {/* Sidebar */}
        <Sidebar />
        {/* Sidebar */}
        {/* children */}
        {children}
        {/* children */}
        
        </body>
    </html>
  );
}
